/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "project.h"
#include<string.h>
#include<stdio.h>

int counter=0;
char name_array[20][20];
int status_array[20];
char address_array[20][20];
int port_array[20];

int *
register_user_1_svc(username arg1,  struct svc_req *rqstp)
{
	static int  result;
	if (0<=counter<20)
	{
		printf("From the server\n");
		strcpy(name_array[counter], arg1);
		status_array[counter]=-1;
		strcpy(address_array[counter],"Empty");
		port_array[counter]=-1;
		printf("Registered user: %s to the server\n",name_array[counter]);
		counter++;
		result = 0;
	}
	else
	{
		result = 1;
	}
	return &result;
}

int *
update_presence_1_svc(username arg1, status arg2, domain_address arg3, port arg4,  struct svc_req *rqstp)
{
	static int  result;
	int j;
	result = 1;
	for (j=0; j<=counter; j++)
	{
		if (strcmp(name_array[j],arg1)==0)
		{
			status_array[j]=arg2;
			strcpy(address_array[j], arg3);
			port_array[j] = arg4;
			result=0;
		}
	}

	return &result;
}

presence_info *
lookup_1_svc(username arg1,  struct svc_req *rqstp)
{
	static presence_info  result;
	int k;
	result = (presence_info){.status0=-1, .domain_address0="empty", .port0 = -1};
	for (k=0; k<=counter; k++)
	{
		if (strcmp(name_array[k],arg1)==0)
		{
			result = (presence_info){.status0=status_array[k], .domain_address0=address_array[k], .port0 = port_array[k]};
		}
	}

	return &result;
}

int *
unregister_1_svc(username arg1,  struct svc_req *rqstp)
{
	static int  result;
	int m;
	int n;
	result = 1;
	for (m=0; m<=counter; m++)
	{
		if (strcmp(name_array[m],arg1)==0)
		{
			for (n=m; n<=counter;n++)
			{
				strcpy(name_array[n],name_array[n+1]);
				status_array[n] = status_array[n+1];
				strcpy(address_array[n],address_array[n+1]);
				port_array[n] = port_array[n+1];
				result = 0;
			}
		}
	}

	return &result;
}
