/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "project.h"


void
user_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	username  register_user_1_arg1;
	int  *result_2;
	username  update_presence_1_arg1;
	status update_presence_1_arg2;
	domain_address update_presence_1_arg3;
	port update_presence_1_arg4;
	presence_info  *result_3;
	username  lookup_1_arg1;
	int  *result_4;
	username  unregister_1_arg1;
	int temp_val;

#ifndef	DEBUG
	clnt = clnt_create (host, user, VER1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	for(;;)
	{
		printf(" \n Enter 0 for exit \n Enter 1 for register \n Enter 2 for update presence \n Enter 3 to lookup user \n Enter 4 to unregister :  ");
		scanf("%d", &temp_val);

		if(temp_val==0)
		{
			printf("Exitting the program \n");
			break;
		}
		else if(temp_val==1)
		{
			char temp[20];
			printf("\n Enter a username to register: ");
			scanf("%s", temp);
			register_user_1_arg1 = temp;

			result_1 = register_user_1(register_user_1_arg1, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
				}
			else
			{
				printf("Response from server: %d \n", *result_1);
			}
		}
		else if (temp_val==2)
		{	
			char temp_arg1[20];
			int temp_arg2;
			char temp_arg3[20];
			int temp_arg4;
			printf("Enter parameters to update\n");
			printf("Enter Username to update: ");
			scanf("%s", temp_arg1);
			printf("Enter Status of %s : ", temp_arg1);
			scanf("%d", &temp_arg2);
			printf("Enter Domain address of %s: ", temp_arg1);
			scanf("%s", temp_arg3);
			printf("Enter port of %s: ", temp_arg1);
			scanf("%d", &temp_arg4);

			update_presence_1_arg1 = temp_arg1;
			update_presence_1_arg2 = temp_arg2;
			update_presence_1_arg3 = temp_arg3;
			update_presence_1_arg4 = temp_arg4;

			result_2 = update_presence_1(update_presence_1_arg1, update_presence_1_arg2, update_presence_1_arg3, update_presence_1_arg4, clnt);
			if (result_2 == (int *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("Response from Server: %d \n", *result_2);
			}
		}
		else if (temp_val==3)
		{
			char temp5[20];
			printf("\n Enter a username to lookup: ");
			scanf("%s", temp5);

			lookup_1_arg1 = temp5;

			result_3 = lookup_1(lookup_1_arg1, clnt);
			if (result_3 == (presence_info *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				if (result_3->status0 == -1)
				{
					printf("There is no record for %s.\n", temp5);
				}
				else
				{
					printf("Response from server: Status: %d,   Domain address: %s, port array: %d \n", result_3->status0, result_3->domain_address0, result_3->port0);
				}
			}
		}
		else if (temp_val==4)
		{
			char temp6[20];
			printf("\n Enter a username to unregister: ");
			scanf("%s", temp6);
			unregister_1_arg1 = temp6;
			result_4 = unregister_1(unregister_1_arg1, clnt);
			if (result_4 == (int *) NULL) 
			{
			clnt_perror (clnt, "call failed");
			}
			else{
				printf("Server response: %d \n", *result_4);
			}
		}
		else
		{
			printf("Enter valid option \n");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	user_1 (host);
exit (0);
}
