/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "project.h"
#include<string.h>
#include<stdio.h>

int counter=0;
char name_array[20][20];
int status_array[20];
char address_array[20][20];
int port_array[20];
char is_broker_array[10][10];
char copy_is_broker[10][10];
char returned_broker[20];

int *
register_user_1_svc(username arg1, is_broker arg2,  struct svc_req *rqstp)
{
	static int  result;
	if (0<=counter<20)
	{
		printf("From the server\n");
		strcpy(name_array[counter], arg1);
		status_array[counter]=-11;
		strcpy(address_array[counter],"Empty");
		port_array[counter]=-11;
		strcpy(is_broker_array[counter],arg2);
		strcpy(copy_is_broker[counter],arg2);
		printf("Registered user: %s to the server\n",name_array[counter]);
		counter++;
		result = 0;
	}
	else
	{
		result = 1;
	}
	return &result;
}

int *
update_presence_1_svc(username arg1, status arg2, domain_address arg3, port arg4, is_broker arg5,  struct svc_req *rqstp)
{
	static int  result;
	int j;
	result = 1;
	for (j=0; j<=counter; j++)
	{
		if (strcmp(name_array[j],arg1)==0)
		{
			status_array[j]=arg2;
			strcpy(address_array[j], arg3);
			port_array[j] = arg4;
			strcpy(is_broker_array[j], arg5);
			strcpy(copy_is_broker[j],arg5);
			printf("Updated presence of %s to the server \n", name_array[j]);
			result=0;
		}
	}

	return &result;
}

presence_info *
lookup_1_svc(username arg1,  struct svc_req *rqstp)
{
	static presence_info  result;
	int k;

	result = (presence_info){.username0="empty", .status0=-1, .domain_address0="empty", .port0 = -1, .is_broker0="-1"};
	for (k=0; k<=counter; k++)
	{
		if (strcmp(name_array[k],arg1)==0)
		{	

			result = (presence_info){.username0 = name_array[k], .status0=status_array[k], .domain_address0=address_array[k], .port0 = port_array[k], .is_broker0=is_broker_array[k]};
			break;
		}
	}
	printf("Returned details of %s \n", arg1 );

	return &result;
}

int *
unregister_1_svc(username arg1,  struct svc_req *rqstp)
{
	static int  result;
	int m;
	int n;
	result = 1;
	for (m=0; m<=counter; m++)
	{
		if (strcmp(name_array[m],arg1)==0)
		{
			for (n=m; n<=counter;n++)
			{
				strcpy(name_array[n],name_array[n+1]);
				status_array[n] = status_array[n+1];
				strcpy(address_array[n],address_array[n+1]);
				port_array[n] = port_array[n+1];
				strcpy(is_broker_array[n], is_broker_array[n+1]);
				strcpy(copy_is_broker[n], copy_is_broker[n+1]);
				
				result = 0;
			}
			printf("Unregistered %s \n", arg1);
		}
	}

	return &result;
}

presence_info *
lookup_broker_1_svc(struct svc_req *rqstp)
{
	static presence_info  result;
	int k;
	char tempo[20];
	result = (presence_info){.username0="empty",.status0=-1, .domain_address0="empty", .port0 = -1, .is_broker0="-1"};
	for (k=0; k<=counter; k++)
	{
		if (strcmp(copy_is_broker[k],"True")==0)
		{
			result = (presence_info){.username0 = name_array[k], .status0=status_array[k], .domain_address0=address_array[k], .port0 = port_array[k], .is_broker0=is_broker_array[k]};
			strcpy(copy_is_broker[k],"Used");
			break;
		}
	printf("Broker lookup: %s \n", copy_is_broker[k]);
	}
	return &result;
}