/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "project.h"

bool_t
xdr_username (XDR *xdrs, username *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_status (XDR *xdrs, status *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_domain_address (XDR *xdrs, domain_address *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_port (XDR *xdrs, port *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_is_broker (XDR *xdrs, is_broker *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_presence_info (XDR *xdrs, presence_info *objp)
{
	register int32_t *buf;

	 if (!xdr_username (xdrs, &objp->username0))
		 return FALSE;
	 if (!xdr_status (xdrs, &objp->status0))
		 return FALSE;
	 if (!xdr_domain_address (xdrs, &objp->domain_address0))
		 return FALSE;
	 if (!xdr_port (xdrs, &objp->port0))
		 return FALSE;
	 if (!xdr_is_broker (xdrs, &objp->is_broker0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_register_user_1_argument (XDR *xdrs, register_user_1_argument *objp)
{
	 if (!xdr_username (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_is_broker (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_presence_1_argument (XDR *xdrs, update_presence_1_argument *objp)
{
	 if (!xdr_username (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_status (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_domain_address (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_port (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_is_broker (xdrs, &objp->arg5))
		 return FALSE;
	return TRUE;
}
