/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "project.h"
#include <zmq.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>
#include <threads.h>

struct targs{
	char *name;
	char *pub;
	char *sub;
};

struct port_pair{
	char client_name[20];
	int client_port;
	int broker_port;
};

int receiver_broker(void *args);
int receiver_client(void *args);
void *context = 0;

FILE *fp;
FILE *fpm;
FILE *fpr;
FILE *fpmr;


void
user_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	username  register_user_1_arg1;
	is_broker register_user_1_arg2;
	int  *result_2;
	username  update_presence_1_arg1;
	status update_presence_1_arg2;
	domain_address update_presence_1_arg3;
	port update_presence_1_arg4;
	is_broker update_presence_1_arg5;
	presence_info  *result_3;
	username  lookup_1_arg1;
	int  *result_4;
	username  unregister_1_arg1;
	presence_info  *result_5;
	int temp_val;

#ifndef	DEBUG
	clnt = clnt_create (host, user, VER1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	for (;;)
	{
		printf(" \n Enter 0 for exit \n Enter 1 for register \n Enter 2 for update presence \n Enter 3 to lookup user \n Enter 4 to unregister user :  \n Enter 5 to lookup broker:  \n Enter 6 to enter chat screen: \n");
		scanf("%d", &temp_val);

		if(temp_val==0)
		{
			printf("Exitting the program \n");
			break;
		}

		else if(temp_val==1)
		{
			char temp_name[20];
			char temp_brok[10];
			printf("\n Enter a username to register: ");
			scanf("%s", temp_name);
			// printf("\n Enter 'True' if the user is a broker else 'False' : ");
			// scanf("%s", temp_brok);


			register_user_1_arg1 = temp_name;
			register_user_1_arg2 = "Def";


			result_1 = register_user_1(register_user_1_arg1, register_user_1_arg2, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
				}
			else
			{
				printf("Response from server: %d \n", *result_1);
			}
		}
		else if (temp_val==2)
		{	
			char temp_arg1[20];
			int temp_arg2;
			char temp_arg3[20];
			int temp_arg4;
			char temp_arg5[10];
			printf("Enter parameters to update\n");
			printf("Enter Username to update: \n");
			scanf("%s", temp_arg1);
			// printf("Enter Status of %s : ", temp_arg1);
			// scanf("%d", &temp_arg2);
			// printf("Enter Domain address of %s: ", temp_arg1);
			// scanf("%s", temp_arg3);
			printf("Enter port of %s: ", temp_arg1);
			scanf("%d", &temp_arg4);
			printf("Enter is broker status of %s: ", temp_arg1);
			scanf("%s", &temp_arg5);

			update_presence_1_arg1 = temp_arg1;
			update_presence_1_arg2 = 3;
			update_presence_1_arg3 = "127.0.0.1";
			update_presence_1_arg4 = temp_arg4;
			update_presence_1_arg5 = temp_arg5;

			result_2 = update_presence_1(update_presence_1_arg1, update_presence_1_arg2, update_presence_1_arg3, update_presence_1_arg4, update_presence_1_arg5, clnt);
			if (result_2 == (int *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("Response from Server: %d \n", *result_2);
			}
		}
		else if (temp_val==3)
		{
			char temp5[20];
			printf("\n Enter a username to lookup: ");
			scanf("%s", temp5);

			lookup_1_arg1 = temp5;

			result_3 = lookup_1(lookup_1_arg1, clnt);
			if (result_3 == (presence_info *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				if (result_3->status0 == -1)
				{
					printf("There is no record for %s.\n", temp5);
				}
				else
				{
					printf("Response from server: Name: %s, Status: %d,   Domain address: %s, port array: %d, Is_Broker: %s \n", result_3->username0,result_3->status0, result_3->domain_address0, result_3->port0, result_3->is_broker0);
				}
			}
		}
		else if (temp_val==4)
		{
			char temp6[20];
			printf("\n Enter a username to unregister: ");
			scanf("%s", temp6);
			unregister_1_arg1 = temp6;
			result_4 = unregister_1(unregister_1_arg1, clnt);
			if (result_4 == (int *) NULL) 
			{
			clnt_perror (clnt, "call failed");
			}
			else{
				printf("Server response: %d \n", *result_4);
			}
		}
		else if (temp_val==5)
		{
			result_5 = lookup_broker_1(clnt);
			if (result_5 == (presence_info *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else{
				if (result_5->status0 == -1)
				{
					printf("There is no record for any broker.\n");
				}
				else
				{
					printf("Response from server: Username: %s, Status: %d,   Domain address: %s, port array: %d, Is_Broker: %s \n", result_5->username0, result_5->status0, result_5->domain_address0, result_5->port0, result_5->is_broker0);
				}	
			}
		}
		else if (temp_val==6)
		{	
			char temp7[20];
			printf("Enter a username to login to chat screen \n");
			scanf("%s",temp7);
			result_3 = lookup_1(temp7, clnt);
			strcpy(temp7,result_3->is_broker0);
			if (result_3 == (presence_info *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{	
				context = zmq_ctx_new();
				thrd_t thrd;

				struct targs ta;
				char curr_port[8];
				char store_port[8];
				char myport[8];
				char tempport[8];
				sprintf(myport, "%d", result_3->port0);
				ta.sub = myport;
				strcpy(store_port, myport);

				if (strcmp(result_3->is_broker0,"True")==0)
				{
					printf("perform broker duties %s \n");
					ta.name = result_3->username0;
					thrd_create(&thrd, receiver_broker, (void *) &ta);
					while(1)
					{
						sleep(4);
						int line_count=0;
						int pair_count=0;
						char line[120];
						struct port_pair pairs_CB_port[200];

						fpr = fopen("port.txt","r");
						while (fgets(line, sizeof(line), fpr))
						{
							char *token;
							token = strtok(line, " ");
							strcpy(pairs_CB_port[pair_count].client_name, token);
							token = strtok(NULL, " ");
							pairs_CB_port[pair_count].client_port = atoi(token);
							token = strtok(NULL, " ");
							pairs_CB_port[pair_count].broker_port = atoi(token);
							pair_count++;
						}
						fclose(fpr);

						fpmr = fopen("chat.txt", "r+");
						while (fgets(line, sizeof(line), fpmr))
						{
							line_count++;
						}
						fclose(fpmr);

						if (line_count>0)
						{
							printf("Last message %s \n", line);
							char message[32];
							char *token;
							strcpy(message, line);
							token = strtok(line, " ");
							printf("Token value %s \n", token);
							result_3 = lookup_1(token, clnt);

							for (int i=0; i<pair_count; i++)
							{
								
								if (strcmp(pairs_CB_port[i].client_name, token)==0)
								{
									sprintf(myport, "%d", pairs_CB_port[i].client_port);
									ta.pub = myport;
									sprintf(curr_port, "%d", pairs_CB_port[i].broker_port);
									printf("Broker port : %s \n",curr_port);
								}
							}

							if (strcmp(store_port,curr_port)==0)
							{
								printf("This Broker's turn to update\n");
								void *publisher = zmq_socket(context, ZMQ_PUB);
								char address[120];
								sprintf(address, "tcp://127.0.0.1:%d", result_3->port0);
								printf("Starting to send message to the other client %s \n", address);

								sleep(4);
								

								int rc = zmq_bind(publisher, address);

								
								assert(rc == 0);
								printf("Binding the port %d \n", result_3->port0);
								
								char old_message[120];
								while(1)
								{
									fpmr = fopen("chat.txt","r+");
									while (fgets(line, sizeof(line),fpmr))
									{	
									}
									fclose(fpmr);
									strcpy(message, line);
									if(strcmp(message, old_message)!=0)
									{	
										sleep(2);
										int count = strlen(message);
										sleep(2);
										printf("Ready to send the message \n");
										rc = zmq_send(publisher, message, count, 0);
										assert(rc == count);
										strcpy(old_message, message);
									}
								}
							}
							
						}	
					}
				}
				else
				{
					printf("Client Side Duties \n");
					ta.name = result_3->username0;
					printf("Name %s \n", ta.name);
					result_5 = lookup_broker_1(clnt);
					if (result_5->status0 != -1)
					{
						char broker_port[8];
						char self_port[8];
						sprintf(self_port, "%d", result_3->port0);
						ta.sub = self_port;
						printf("Self Port:%s \n", ta.sub);

						sprintf(broker_port, "%d", result_5->port0);

						ta.pub = broker_port;
						printf("Publisher Port:%s \n", ta.pub);


						FILE *fp;
						fp = fopen("port.txt","a+");
						fprintf(fp, "%s %d %d\n", ta.name, result_3->port0, result_5->port0);
						fclose(fp);


						thrd_create(&thrd, receiver_client, (void *) &ta);

						void *publisher = zmq_socket(context, ZMQ_PUB);
						char address[120];
						sprintf(address, "tcp://127.0.0.1:%s", ta.pub);
						printf("Connected to broker: %s \n", ta.pub);
						int rc = zmq_bind(publisher, address);
						assert(rc==0);

						char buf[120];
						while(1)
						{
							fgets(buf, 120, stdin);
							buf[strcspn(buf,"\n")] = 0;
							int count = strlen(buf);
							rc = zmq_send(publisher,buf, count,0);
							assert(rc == count);
						}
						zmq_close(publisher);
					}
					else
					{
						printf("No broker found \n");
					}
				}
			}
		}
		else
		{
			printf("Enter valid option \n");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int receiver_broker(void *args)
{
	struct targs  *ta = (struct targs *) args;
	void *subscriber = zmq_socket(context, ZMQ_SUB);
	char address[120];
	sprintf(address, "tcp://127.0.0.1:%s", ta->sub);
	printf("Subscribing to %s \n", address);
	int rc = zmq_connect(subscriber, address);
	assert(rc==0);
	rc = zmq_setsockopt(subscriber, ZMQ_SUBSCRIBE, "", 0);
	assert (rc==0);

	char message[120];
	while(1){
		fpm = fopen("chat.txt","a+");
		rc = zmq_recv(subscriber, message, 120, 0);
		assert (rc != -1);
		printf("Received message %s \n", message);
		fprintf(fpm, "%s \n", message);
		fclose(fpm);
	}
	zmq_close(subscriber);
	zmq_ctx_destroy(context);

	return 0;
}

int receiver_client(void *args)
{
	struct targs *ta = (struct targs *) args;
	void *subscriber = zmq_socket(context, ZMQ_SUB);
	char address[120];
	sprintf(address, "tcp://127.0.0.1:%s", ta->sub);
	printf("Subscribing to %s \n", address);
	int rc = zmq_connect(subscriber, address);
	assert(rc==0);
	rc = zmq_setsockopt(subscriber, ZMQ_SUBSCRIBE, ta->name, strlen(ta->name));
	assert (rc==0);

	char message[120];
	while(1){

		rc = zmq_recv(subscriber, message, 120, 0);
		assert (rc != -1);
		printf("%s \n", message);
	}
	zmq_close(subscriber);
	zmq_ctx_destroy(context);

	return 0;


}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	user_1 (host);
exit (0);
}