/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "project.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_register_user_1 (register_user_1_argument *argp, struct svc_req *rqstp)
{
	return (register_user_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_update_presence_1 (update_presence_1_argument *argp, struct svc_req *rqstp)
{
	return (update_presence_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, rqstp));
}

static presence_info *
_lookup_1 (username  *argp, struct svc_req *rqstp)
{
	return (lookup_1_svc(*argp, rqstp));
}

static int *
_unregister_1 (username  *argp, struct svc_req *rqstp)
{
	return (unregister_1_svc(*argp, rqstp));
}

static presence_info *
_lookup_broker_1 (void  *argp, struct svc_req *rqstp)
{
	return (lookup_broker_1_svc(rqstp));
}

static void
user_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		register_user_1_argument register_user_1_arg;
		update_presence_1_argument update_presence_1_arg;
		username lookup_1_arg;
		username unregister_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case register_user:
		_xdr_argument = (xdrproc_t) xdr_register_user_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _register_user_1;
		break;

	case update_presence:
		_xdr_argument = (xdrproc_t) xdr_update_presence_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _update_presence_1;
		break;

	case lookup:
		_xdr_argument = (xdrproc_t) xdr_username;
		_xdr_result = (xdrproc_t) xdr_presence_info;
		local = (char *(*)(char *, struct svc_req *)) _lookup_1;
		break;

	case unregister:
		_xdr_argument = (xdrproc_t) xdr_username;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _unregister_1;
		break;

	case lookup_broker:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_presence_info;
		local = (char *(*)(char *, struct svc_req *)) _lookup_broker_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (user, VER1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, user, VER1, user_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (user, VER1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, user, VER1, user_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (user, VER1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
